#!/bin/bash -l


# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "=========================================================="



module load R/3.4.0

Rscript  /restricted/projectnb/chengcancer/Simon/project/T2D/bulk_RNA-seq/merge_170415_NB501164_170506_NB501164/2mapping/QT/osteoblast/smallest_pval_data/osteo_enrichment.R  ${eQTLfilePath} ${GWASfilePath} ${GTeX_eQTLpvalueUpperBound} ${GTeX_eQTLpvalueLowerBound}  ${sigGWASpvalueCutoff}  ${outdir}



